// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbAOgWOZ-W3Lnq_vVr6HXY_s7I2I7d3DM',
    appId: '1:484800002915:web:8c81c9fc078b31212b7156',
    messagingSenderId: '484800002915',
    projectId: 'ridesharinglatest',
    authDomain: 'ridesharinglatest.firebaseapp.com',
    databaseURL: 'https://ridesharinglatest-default-rtdb.firebaseio.com',
    storageBucket: 'ridesharinglatest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD178a4bKU7NF3FU09AKxuCCCOQte4Nj4g',
    appId: '1:484800002915:android:98d19b4c1ebb2f8f2b7156',
    messagingSenderId: '484800002915',
    projectId: 'ridesharinglatest',
    databaseURL: 'https://ridesharinglatest-default-rtdb.firebaseio.com',
    storageBucket: 'ridesharinglatest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Um_tRvYTz1ybhnJPZcjXqon7ENDWv7c',
    appId: '1:484800002915:ios:32b7ded3fca9a2002b7156',
    messagingSenderId: '484800002915',
    projectId: 'ridesharinglatest',
    databaseURL: 'https://ridesharinglatest-default-rtdb.firebaseio.com',
    storageBucket: 'ridesharinglatest.appspot.com',
    iosClientId: '484800002915-kkrdcd431e9349n342o4mcdo4737nr1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8Um_tRvYTz1ybhnJPZcjXqon7ENDWv7c',
    appId: '1:484800002915:ios:32b7ded3fca9a2002b7156',
    messagingSenderId: '484800002915',
    projectId: 'ridesharinglatest',
    databaseURL: 'https://ridesharinglatest-default-rtdb.firebaseio.com',
    storageBucket: 'ridesharinglatest.appspot.com',
    iosClientId: '484800002915-kkrdcd431e9349n342o4mcdo4737nr1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRide',
  );
}
